In [1]:
import pandas as pd
import numpy as np

In [2]:
charts = pd.read_csv('newish.csv')
charts

,Unnamed: 0,rank,previous_week,artist,album,label,weeks_on_chart,calendar_week,year,country
0,0,1,1,Rui Veloso,O concerto acústico,Virgin,8,1,2004,PT
1,1,2,3,Robbie Williams,Live Summer 2003,Chrysalis,14,1,2004,GB
2,2,3,2,Tribalistas,Tribalistas,Emi,42,1,2004,BR
3,3,4,4,Linkin Park,Live In Texas,Wb,7,1,2004,US
4,4,5,6,Tony Carreira,Ao vivo no pavilhao atlantico,Espacial,22,1,2004,PT
...,...,...,...,...,...,...,...,...,...,...
24805,24805,26,35,Pink Floyd,The Wall,Warner,64,52,2019,GB
24806,24806,27,32,António Variações,O melhor de António Variações,Warner,23,52,2019,PT
24807,24807,28,22,João Pedro Pais,Confidências (de um homem vulgar),Sony Music,10,52,2019,PT
24808,24808,29,23,Camila Cabello,Romance,Sony Music,3,52,2019,US
24809,24809,30,18,Jose Mário Branco,Canções escolhidas,Warner,11,52,2019,PT

In [3]:
pt_art = charts.loc[charts["country"] == "PT"]["artist"]
#pt_art.to_csv("pt_art.csv")
pt_art

0               Rui Veloso
4            Tony Carreira
8            Luís Represas
13         Pedro Abrunhosa
14                  Mariza
               ...
24803               Mariza
24804          Marco Paulo
24806    António Variações
24807      João Pedro Pais
24809    Jose Mário Branco
Name: artist, Length: 11868, dtype: object

In [4]:
flourish = pd.read_csv('flourish.csv')
flourish

,Unnamed: 0,rank,previous_week,artist,album,label,weeks_on_chart,calendar_week,year,country
0,0,1,1,Rui Veloso,O concerto acústico,Virgin,8,1,2004,PT
1,4,5,6,Tony Carreira,Ao vivo no pavilhao atlantico,Espacial,22,1,2004,PT
2,8,9,9,Luís Represas,Fora de mão,Mercury,10,1,2004,PT
3,13,14,13,Pedro Abrunhosa,Palco,Polydor,6,1,2004,PT
4,14,15,8,Mariza,Fado curvo,Virgin,40,1,2004,PT
...,...,...,...,...,...,...,...,...,...,...
11863,24803,24,26,Mariza,Mariza [2018],Warner,84,52,2019,PT
11864,24804,25,21,Marco Paulo,As nossas canções,Sony Music,21,52,2019,PT
11865,24806,27,32,António Variações,O melhor de António Variações,Warner,23,52,2019,PT
11866,24807,28,22,João Pedro Pais,Confidências (de um homem vulgar),Sony Music,10,52,2019,PT
11867,24809,30,18,Jose Mário Branco,Canções escolhidas,Warner,11,52,2019,PT

In [6]:
flourish = flourish[["artist","album"]]

top_10 = ['Mariza', 'Tony Carreira', 'Ana Moura', 'António Zambujo', 'Panda e Os Caricas', 'Deolinda', 'Carminho', 'Paulo Gonzo', 'D.A.M.A.', 'Pedro Abrunhosa']
tabela_final = flourish[flourish['artist'].isin(top_10)].copy()
tabela_final.artist.value_counts()

Mariza                968
Tony Carreira         641
Ana Moura             616
António Zambujo       412
Panda e Os Caricas    326
Deolinda              306
Carminho              299
Paulo Gonzo           239
D.A.M.A.              221
Pedro Abrunhosa       178
Name: artist, dtype: int64

In [8]:
tabela_final.groupby(['artist', 'album']).count()

tabela_final.to_csv("flourish-real.csv")